---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность фильтровать товары
non-functional:
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
implicit:
  - Пароль при входе на сайт должен быть замаскирован
  - Пользователь должен иметь возможность удалять товары из корзины
  - Пользователь должен иметь возможность уменьшать количество товаров из корзины
  - Пользователь должен иметь возможность добавлять товары в "избранное"
