---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность фильтровать товары
non-functional:
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть доступен на различных устройствах
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
implicit:
  - Должна быть кнопка явного уменьшения или увеличения количества товаров, добавленных в корзину
  - На карточке товара должна быть указана скидка на товар
  - В корзине должна быть указана скидка на товар
  - Товар должен добавляться в корзину  при первом нажатии на кнопку "В корзину"
  - В кнопке "Категория" должны отражаться все имеющиеся категории товаров
  - Должна быть кнопка подтверждения заказа
  - Закрытие модального окна с заказом должно быть возможным при нажатии на кнопку закрытия
  - Удаление содержимого карзины должно происходить с подтверждением
  - При установки фильтра на цену цена товара не должна быть отрицательной
  - При нажатии на кнопку Store переход на главную страницу должен происходить с первого клика
